spring:
  profiles:
    active:
     - dev

--- 
server:
  port: 7001
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-eureka-config-dev
eureka:
  instance:
   hostname: eureka7001.com  # eureka服务器端的实例名称 由localhost改为eureka7001.com
  client:
   register-with-eureka: false  # false标识不向注册中心注册自己
   fetch-registry: false  #false表示自己就是注册中心，不需要检索服务
  
---
server:
  port: 7002
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-eureka-config-test
eureka:
  instance:
   hostname: eureka7002.com  # eureka服务器端的实例名称 由localhost改为eureka7001.com
  client:
   register-with-eureka: false  # false标识不向注册中心注册自己
   fetch-registry: false  #false表示自己就是注册中心，不需要检索服务
# 以utf-8格式保存
